name: Docker Image CI

on:
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - run: docker build . -t kmonad-builder

      - run: docker run --rm -v ${PWD}:/host/ kmonad-builder bash -c 'cp -vp /root/.local/bin/kmonad /host/'

      - uses: actions/upload-artifact@v4
        with:
          name: kmonad-binary
          path: kmonad
